apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: docker
          image: docker:27.1.1-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
        - name: taskmanager
          ## image: your custom docker image
          args: ["taskmanager"]
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
          ports:
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query-state
          livenessProbe:
            tcpSocket:
              port: 6122
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf/
              readOnly: false
            - name: beam-artifact-staging
              mountPath: "/tmp/beam-artifact-staging"
          securityContext:
            runAsUser: 9999
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: beam-artifact-staging
          persistentVolumeClaim:
            claimName: flink-vol
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j-console.properties
                path: log4j-console.properties
---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-service
  namespace: flink
spec:
  type: NodePort
  selector:
    app: flink
    component: taskmanager
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30000
