apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-beam-jobserver
  namespace: spark
spec:
  serviceName: spark-headless
  selector:
    matchLabels:
      app: spark-beam-jobserver
  template:
    metadata:
      labels:
        app: spark-beam-jobserver
        app.kubernetes.io/instance: custom_spark
        app.kubernetes.io/name: spark
    spec:
      containers:
        - name: spark-beam-jobserver
          image: apache/beam_spark3_job_server:2.55.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
              name: jobservice
            - containerPort: 8098
              name: artifact
            - containerPort: 8097
              name: expansion
          volumeMounts:
            - name: beam-artifact-staging
              mountPath: "/tmp/beam-artifact-staging"
          command:
            [
              "/bin/bash",
              "-c",
              "./spark-job-server.sh --job-host=<HOST_HERE> --job-port=8099 --artifact-port=8098 --expansion-port=-1 --spark-master-url=spark://spark-primary:7077",
            ]
            # you can change the host, port and flink master url default: --job-host=localhost | example in k8s deployment --job-host=spark-beam-jobserver.spark.svc.cluster.local
            # means the expansion port will not be used by the worker server. If it is active, the pod will not go up.
            # expansion-port = -1 
      volumes:
        - name: beam-artifact-staging
          persistentVolumeClaim:
            claimName: spark-beam-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: spark-beam-jobserver
  namespace: spark
  labels:
    app: spark-beam-jobserver
spec:
  selector:
    app: spark-beam-jobserver
  type: NodePort
  ports:
    - port: 8099
      nodePort: 32090
      name: job-service
    - port: 8098
      nodePort: 32091
      name: artifacts
