apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-children
  namespace: spark
spec:
  serviceName: spark-headless
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
        component: children
        app.kubernetes.io/instance: custom_spark
        app.kubernetes.io/name: spark
    spec:
      containers:
        - name: docker
          image: docker:27.1.1-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
          ports:
            - name: dind-con-port
              containerPort: 2375
              protocol: TCP
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
        - name: children
          image: <custom_image_here>
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-primary:7077"
            - name: SPARK_WORKER_MEMORY
              value: "2G"
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
          ports:
            - containerPort: 8081
              name: ui
          volumeMounts:
            - name: beam-artifact-staging
              mountPath: "/tmp/beam-artifact-staging"
          resources:
            limits:
              cpu: "2"
              memory: "2G"
      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: beam-artifact-staging
          persistentVolumeClaim:
            claimName: spark-beam-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spark-children
  labels:
    app: spark
    component: children
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
  selector:
    app: spark
    component: children
---
apiVersion: v1
kind: Service
metadata:
  name: spark-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: custom_spark
    app.kubernetes.io/name: spark
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: spark
spec:
  ports:
    - port: 2375
      protocol: TCP
  selector:
    app: spark
    component: docker