apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-primary
  namespace: spark
spec:
  serviceName: spark-headless
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: primary
  template:
    metadata:
      labels:
        app: spark
        component: primary
        app.kubernetes.io/instance: custom_spark
        app.kubernetes.io/name: spark
    spec:
      containers:
        - name: primary
          image: docker.io/bitnami/spark:3.2.2
          env:
          - name: SPARK_MODE
            value: "master"
          - name: SPARK_RPC_AUTHENTICATION_ENABLED
            value: "no"
          - name: SPARK_RPC_ENCRYPTION_ENABLED
            value: "no"
          - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
            value: "no"
          - name: SPARK_SSL_ENABLED
            value: "no"
          ports:
            - containerPort: 7077
              name: masterendpoint
            - containerPort: 8080
              name: ui
            - containerPort: 7078
              name: driver-rpc-port
            - containerPort: 7079
              name: blockmanager
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-primary
  namespace: spark
  labels:
    app: spark
    component: primary
spec:
  type: ClusterIP
  ports:
    - name: masterendpoint
      port: 7077
      targetPort: 7077
    - name: rest
      port: 6066
      targetPort: 6066
    - name: ui
      port: 8080
      targetPort: 8080
    - name: driver-rpc-port
      protocol: TCP
      port: 7078
      targetPort: 7078
    - name: blockmanager
      protocol: TCP
      port: 7079
      targetPort: 7079
  selector:
    app: spark
    component: primary
---
apiVersion: v1
kind: Service
metadata:
  name: spark-headless
  namespace: spark
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: custom_spark
    app.kubernetes.io/name: spark
  ports:
    - name: spark
      port: 7077
